"""Added user attributes

Revision ID: 39f3120b1531
Revises: fd9749a6f0ab
Create Date: 2019-03-07 18:56:18.420237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39f3120b1531'
down_revision = 'fd9749a6f0ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birthday', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(length=6), nullable=True))
    op.add_column('user', sa.Column('privacy', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('state', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('zip_code', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'zip_code')
    op.drop_column('user', 'state')
    op.drop_column('user', 'privacy')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'city')
    op.drop_column('user', 'birthday')
    # ### end Alembic commands ###
